spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt-ghi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  proxy:
    ip: 127.0.0.1
    port: 1080

openAi:
  config:
    apiKey: sxxxx
    organizationName: xxx
    organizationId: xxxxx

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted     # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1           # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0       # 逻辑未删除值(默认为 0)